services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_HTTP_PORTS=5000
    ports:
       - "5000:5000"
    depends_on:
       - database

  database:
     container_name: database
     image: postgres:13
     environment:
       POSTGRES_DB: developer
       POSTGRES_USER: developer
       POSTGRES_PASSWORD: developer
     ports:
       - "5432:5432"
     restart: unless-stopped    

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database